version: "3.8"

services:
  database_ignite:
    image: postgres # imagem já existe no docker hub
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      # variáveis disponíveis para uso estão na documentação 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    # orquestra a imagem criada no Dockerfile
    build: . # executa o mesmo comando do terminal na nossa raiz (docker build -t rentx .)
    container_name: rentx
    ports:
      - 3000:3000 # mapeamento de portas
    volumes:
      - .:/usr/app # . -> pegando todas as informações do diretório atual | :/usr/app -> passando para o WORKDIR criado
    links:
      #ligação entre containers, permitindo que o container de destino (api) tenha informações do container de origem(database). 
      - database_ignite
    depends_on:
      #define que o app depende do database, isso fará com que a ordem para os containers subirem seja primeiro o serviço database e depois o da api.
      - database_ignite

volumes:
  # referência para o volume criado no database
  pgdata:
    driver: local
